import jsPDF from 'jspdf';
import { CompanyInfo } from '@/features/company/types';

export const addPdfFooter = (doc: jsPDF) => {
  const pageCount = doc.getNumberOfPages();
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // 1. Draw page border frame (5mm margin top/left/right, 15mm from bottom)
    doc.setLineWidth(0.3);
    doc.setDrawColor(0, 0, 0);
    doc.rect(5, 5, width - 10, height - 15);

    // 2. Set footer text styling
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128); // Gray color
    doc.setFont('helvetica', 'italic');

    // Center text: Generated by Morex Technologies ERP
    doc.text('Generated by Morex Technologies ERP', width / 2, height - 4, { align: 'center' });

    // Page number on bottom right
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${pageCount}`, width - 14, height - 4, { align: 'right' });
  }
};

export const addPdfHeader = (
  doc: jsPDF,
  companyInfo: CompanyInfo | null,
  title: string,
  subTitle?: string
) => {
  const width = doc.internal.pageSize.getWidth();
  const margin = 14;
  // const logoY = 10;
  // const logoHeight = 25;
  let textY = 15;

  // 1. Company Logo
  /* 
    let logoBottomY = 0;
    if (companyInfo?.logoUrl) {
        try {
            // Check if logoUrl is a data URL (base64) or a remote URL
            // We try to add it if it's a valid image data.
            doc.addImage(companyInfo.logoUrl, 'PNG', margin, logoY, 25, logoHeight);
            logoBottomY = logoY + logoHeight;
        } catch (e) {
            console.error("Could not add logo to PDF", e);
        }
    }
    */

  // 2. Company Name & Details (Centered)
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);

  // Company Name
  const companyName = companyInfo?.companyName || 'DMOR PAINTS';
  doc.text(companyName.toUpperCase(), width / 2, textY, { align: 'center' });

  /*
    // Company Address / Contact
    textY += 6;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    if (companyInfo?.companyId) { // Ensure company info exists
        // 1. Address Handling (Split into max 2 lines)
        if (companyInfo.address) {
            // Split address by newlines first
            const rawLines = companyInfo.address.split('\n');
            let addressLines: string[] = [];

            // If explicit newlines exist, take top 2
            if (rawLines.length > 1) {
                addressLines = rawLines.slice(0, 2);
            } else {
                // Otherwise check length and split if too long (rough char count for 9pt font)
                const addr = rawLines[0];
                if (addr.length > 60) {
                    // Find a space near the middle
                    const midpoint = Math.floor(addr.length / 2);
                    const splitIndex = addr.indexOf(' ', midpoint);
                    if (splitIndex !== -1 && splitIndex < 60) {
                        addressLines = [addr.substring(0, splitIndex), addr.substring(splitIndex + 1)];
                    } else {
                        // Just split at 60
                        addressLines = doc.splitTextToSize(addr, 120); // approx width in mm
                    }
                } else {
                    addressLines = [addr];
                }
            }

            // Print Address Lines
            addressLines.slice(0, 2).forEach(line => {
                doc.text(line.trim(), width / 2, textY, { align: 'center' });
                textY += 5; // spacing between address lines
            });
        }

        // 2. Contact Details (New Row)
        const contactParts: string[] = [];
        if (companyInfo.contactNumber) contactParts.push(`Ph: ${companyInfo.contactNumber}`);
        if (companyInfo.email) contactParts.push(companyInfo.email);

        if (contactParts.length > 0) {
            // Add a bit extra padding before contact info if address was printed
            if (companyInfo.address) textY += 1;
            doc.text(contactParts.join(' | '), width / 2, textY, { align: 'center' });
            textY += 6;
        } else {
            textY += 2;
        }
    } else {
        textY += 2;
    }
    */

  // Simplification: We only have Company Name now.
  textY += 5; // Add a small margin below company name

  // Ensure we start below whichever is taller (Logo or Text)
  // Add some padding (5 units)
  let currentY = textY + 5;

  // Safety check for NaN
  if (isNaN(currentY)) {
    console.error('addPdfHeader calculated NaN for currentY, falling back to 50');
    currentY = 50;
  }

  // Divider Line
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, currentY, width - margin, currentY);

  // 3. Report Title (Below Divider)
  currentY += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(title, margin, currentY);

  // Subtitle (if any)
  if (subTitle) {
    currentY += 6;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(subTitle, margin, currentY);
  }

  console.log(`addPdfHeader finished. Next Y: ${currentY + 5}`);
  // Return the Y position where the next component can start
  return currentY + 5;
};
